export const optionsButtons = [
  {
    buttonTitle: "Cadastramento",
    optionsList: [
      "Chamamento Público",
      "Listar Programas",
      "Consultar Programas",
    ],
  },
  {
    buttonTitle: "Acomp. e Fiscalização",
    optionsList: [
      "Agendar - Fiscais, Supervisores e Terceiros",
      "Bloqueios/Desbloqueios da Execução Financeira do Convênio - Solicitações",
      "Esclarecimentos",
      "Mensagens de Acompanhamento",
      "Notificação Prévia Inadimplência",
      "Notificações de Irregularidades",
      "Relatório Convênio - Acompanhamento",
      "Relatório Fotográfico",
      "Relatório de Aceite de Licitação",
      "Relatório de Acompanhamento - Itens de Despesas (PAD)",
      "Vincular - Fiscais, Supervisores e Terceiros",
    ],
  },
  {
    buttonTitle: "Programas",
    optionsList: [
      "Chamamento Público",
      "Consultar Programas",
      "Listar Programas",
    ],
  },
  {
    buttonTitle: "Prestação de Contas",
    optionsList: [
      "Antecipação/Estorno Prestação Contas",
      "Consultar Convênios",
      "Histórico",
      "Notificação Prévia Inadimplência",
      "Prestar Contas",
    ],
  },
  {
    buttonTitle: "Propostas",
    optionsList: [
      "Consultar Declarações",
      "Consultar Propostas",
      "Copiar Proposta",
      "Dados da Proposta/Pré-Convênio/Convênio",
      "Histórico",
      "Incluir Declarações",
      "Incluir Proposta",
      "Pareceres",
    ],
  },
  {
    buttonTitle: "Administração",
    optionsList: ["Manter Termo Integração"],
  },
  {
    buttonTitle: "Execução",
    optionsList: [
      "Aplicação em Poupança",
      "Apostilamento",
      "Autorizar Movimentação FinanceiraAplicação em Poupança",
      "Apostilamento",
      "Autorizar Movimentação Financeira",
      "Cadastrar Credor da Transferência Voluntária",
      "Cancelar Movimentação Financeira",
      "Classificar Ingresso de Recursos",
      "Complementar Dados de Câmbio do Documento de Liquidação",
      "Conciliação Bancária",
      "Consultar Convênios Reservados",
      "Consultar Convênios/Pré-Convênios",
      "Consultar Documento de Liquidação",
      "Consultar Domicílio Bancário Credor",
      "Consultar Tributos / Contribuições / Retenções",
      "Conta Bancária",
      "Contratos",
      "Devolução de Recursos",
      "Discriminar OBTV",
      "Extrato Bancário do Convênio",
      "Incluir Documento de Liquidação",
      "Listar Movimentações Financeiras",
      "Ordenador Despesa OBTV",
      "Pagamento",
      "Pagamento com OBTV",
      "Processo de Compra",
      "Prorroga de Ofício",
      "Realizar Eventos/Retificações",
      "Recolher Tributo / Pagar Contribuição com OBTV",
      "Registrar Notificação",
      "Registro Execução Termo de Parceria",
      "Registro Ingresso de Recurso",
      "Reiniciar Senha OBTV",
      "Relatórios Execução",
      "Termos Aditivos",
    ],
  },
  {
    buttonTitle: "TCE",
    optionsList: [
      "Consultar TCE Instaurada na Plataforma +Brasil",
      "Consultar TCE Instaurada no e-TCE",
    ],
  },
  {
    buttonTitle: "Inf. Gerenciais",
    optionsList: ["Baixar Inf. Gerenciais"],
  },
  {
    buttonTitle: "Verificação de Regularidade",
    optionsList: [
      "Consultar Adimplência do Ente/Entidade",
      "Consultar Registro de Irregularidade",
      "Extrato - Registro de Irregularidades",
    ],
  },
  {
    buttonTitle: "Cadastros",
    optionsList: [
      "Alterar Meus Dados",
      "Consultar Funcionalidades",
      "Consultar Participante",
      "Manter Apetite ao Risco",
    ],
  },
];

export const messages = [
  "s simply dummy text of the printing and typesetting industry remaining essentially unchanged, s simply dummy ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius rhoncus leo at cursus. Mae bibendum orci. Nulla fringilla sapien nulla.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius rhoncus leo at cursus. Mae bibendum orci. Nulla fringilla sapien nulla.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius rhoncus leo at cursus. Mae bibendum orci. Nulla fringilla sapien nulla.",
  "s simply dummy text of the printing and typesetting industry remaining essentially unchanged, s simply dummy ",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius rhoncus leo at cursus. Mae bibendum orci",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius rhoncus leo at cursus. Mae bibendum orci",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius rhoncus leo at cursus. Mae bibendum orci",
];
